# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardIndent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('card_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_conn_type', models.CharField(max_length=10)),
                ('client_sv_adr', models.CharField(max_length=100)),
                ('client_log', models.CharField(max_length=100)),
                ('client_pass', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client_config',
            },
        ),
        migrations.CreateModel(
            name='FuelOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_id', models.BigIntegerField()),
                ('fuel_out_start', models.DateTimeField()),
                ('fuel_out_end', models.DateTimeField()),
                ('fuel_in_quantity', models.FloatField()),
                ('fuel_out_quantity', models.FloatField()),
                ('fuel_out_rfid', models.IntegerField()),
                ('fuel_out_name', models.CharField(max_length=100)),
                ('fuel_out_wh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'out_fuel',
            },
        ),
        migrations.CreateModel(
            name='TrkConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trk_oid', models.IntegerField()),
                ('client_sensors_name', models.CharField(max_length=200)),
                ('trk_type', models.IntegerField()),
            ],
            options={
                'db_table': 'trk_config',
            },
        ),
    ]
