# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_out', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trkconfig',
            name='trk_client_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
