# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_out', '0002_trkconfig_trk_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trkconfig',
            old_name='trk_client_id',
            new_name='trk_cln_id',
        ),
    ]
