# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_out', '0003_auto_20170907_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_conn_type', models.CharField(max_length=10)),
                ('customer_sv_adr', models.CharField(max_length=100)),
                ('customer_log', models.CharField(max_length=100)),
                ('customer_pass', models.CharField(max_length=100)),
                ('customer_sv_type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Customer_config',
            },
        ),
        migrations.CreateModel(
            name='FuelReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_data', models.TimeField()),
                ('fuel_number', models.IntegerField()),
                ('fuel_trk_name', models.CharField(max_length=10)),
                ('fuel_summary_out', models.IntegerField()),
                ('fuel_summary_in', models.IntegerField()),
                ('fuel_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_out.CustomerConfig')),
            ],
            options={
                'db_table': 'report_days',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_id', models.CharField(max_length=15)),
                ('ware_in', models.FloatField()),
                ('ware_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_out.CustomerConfig')),
            ],
            options={
                'db_table': 'ware house',
            },
        ),
        migrations.DeleteModel(
            name='ClientConfig',
        ),
        migrations.AddField(
            model_name='fuelout',
            name='fuel_trk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fuel_out.TrkConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trkconfig',
            name='trk_name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardindent',
            name='card_customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fuel_out.CustomerConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelout',
            name='fuel_customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fuel_out.CustomerConfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trkconfig',
            name='trk_customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fuel_out.CustomerConfig'),
            preserve_default=False,
        ),
    ]
