# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_out', '0004_auto_20170910_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelout',
            name='fuel_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuelout',
            name='fuel_in_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fuelout',
            name='fuel_out_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fuelout',
            name='fuel_out_rfid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuelreports',
            name='fuel_summary_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuelreports',
            name='fuel_summary_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trkconfig',
            name='trk_cln_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trkconfig',
            name='trk_type',
            field=models.IntegerField(default=0),
        ),
    ]
